version: "3.8"

volumes:
  rabbitmq_data:

services:

  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq


  ####################################
  # Fairprice: The fairprice service
  ####################################
  fairprice:
    build:
      context: ./
      dockerfile: fairprice.Dockerfile
    image: douglastoh/fairprice:uchef
    restart: always
    environment:
      dbURL: 'mysql+pymysql://root:root@host.docker.internal:3306/fairprice'
      PYTHONUNBUFFERED: 1
    ports:
      - "5003:5003"
      
  ####################################
  # Cold Storage: The cold storage service
  ####################################
  coldStorage:
    build:
      context: ./
      dockerfile: coldStorage.Dockerfile
    image: douglastoh/coldstorage:uchef
    restart: always
    environment:
      dbURL: 'mysql+pymysql://root:root@host.docker.internal:3306/coldStorage'
      PYTHONUNBUFFERED: 1
    ports:
      - "5004:5004"

  ####################################
  # Error: The error service
  ####################################
  error:
    build:
      context: ./
      dockerfile: error.Dockerfile
    image: douglastoh/error:uchef
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
  
  ####################################
  # Order: The order service
  ####################################
  order:
    build:
      context: ./
      dockerfile: order.Dockerfile
    image: douglastoh/order:uchef
    restart: always
    depends_on:
      - fairprice
      - coldStorage
    environment:
      fairprice_url: http://host.docker.internal:5003/supermarketStock
      coldStorage_url: http://host.docker.internal:5004/supermarketStock
      PYTHONUNBUFFERED: 1
    ports:
      - "5002:5002"
  
  ####################################
  # Notification: The notification service
  ####################################
  notification:
    build:
      context: ./
      dockerfile: notification.Dockerfile
    image: douglastoh/notification:uchef
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5006:5006"

  ####################################
  # Payment: The payment service
  ####################################
  payment:
    build:
      context: ./
      dockerfile: payment.Dockerfile
    image: douglastoh/payment:uchef
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5005:5005"

  ####################################
  # Recipe: The recipe service
  ####################################
  recipe:
    build:
      context: ./
      dockerfile: recipe.Dockerfile
    image: douglastoh/recipe:uchef
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5008:5008"  

  ####################################
  # Place Delivery: The place delivery service
  ####################################
  place_delivery:
    build:
      context: ./
      dockerfile: place_delivery.Dockerfile
    image: douglastoh/place_delivery:uchef
    restart: always
    depends_on:
      - fairprice
      - coldStorage
      - order
      - notification
      - payment
      - recipe
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5001:5001"

  ####################################
  # Get Delivery Status: The get delivery status service 
  ####################################
  get_delivery_status:
    build:
      context: ./
      dockerfile: get_delivery_status.Dockerfile
    image: douglastoh/get_delivery_status:uchef
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  ####################################
  # Supermarket form: The surpermarket form service 
  ####################################
  supermarket_form:
    build:
      context: ./
      dockerfile: supermarket_form.Dockerfile
    image: douglastoh/supermarket_form:uchef
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
    ports:
      - "5100:5100"
